// day06-react/01-web0521/07-src-todos案例-使用pubsub-js优化/components/Footer/Footer.js
import React, { Component } from 'react'
import './Footer.css'
export default class Footer extends Component {
  render() {
    const {list} = this.props 
    // 计算总共有多少条和完成了多少条
    const allTotal = list.length 
    const doneTotal = list.filter(item=>item.isDone).length 


    return (
      <div className="todo-footer">
        <label>
          {/* 如果数据中的任务项都选中了,点击全选,就一定会变成都不选中. 如果上面的任务项有一个没选中,点击全选就一定是将上面的任务项都变成选中 */}
          <input type="checkbox" checked={doneTotal === allTotal} onChange={this.props.allCheckHandle}/>
        </label>
        <span>
          <span>已完成 {doneTotal}</span> / 全部 {allTotal}
        </span>
        <button className="btn btn-danger" onClick={this.props.delDoneHandle}>清除已完成任务</button>
      </div>
    )
  }
}

// day18-vue2.0/01-web0521-vue/03-src-todos案例-传统实现/components/Footer.vue
<template>
  <div class="todo-footer">
    <label>
      <input type="checkbox" v-bind:checked="doneTotal === allTotal" @change="updateAll($event.target.checked)"/>
    </label>
    <span> <span>已完成{{doneTotal}}</span> / 全部{{allTotal}} </span>
    <button class="btn btn-danger" @click="deleteAllDone">清除已完成任务</button>
  </div>
</template>

<script>
export default {
  props: ['doneTotal','allTotal','updateAll',"deleteAllDone"]
}
</script>

<style>
/*footer*/
.todo-footer {
  height: 40px;
  line-height: 40px;
  padding-left: 6px;
  margin-top: 5px;
}

.todo-footer label {
  display: inline-block;
  margin-right: 20px;
  cursor: pointer;
}

.todo-footer label input {
  position: relative;
  top: -1px;
  vertical-align: middle;
  margin-right: 5px;
}

.todo-footer button {
  float: right;
  margin-top: 5px;
}
</style>
