// day06-react/01-web0521/01-src-todos案例基本完成/components/List/List.js
import React, { Component } from 'react'
import Item from '../Item/Item'
import './List.css'
export default class List extends Component {
  render() {
    const { list, updateTodo,deleteTodo } = this.props
    return (
      <ul className="todo-main">
        {list.map((item) => (
          <Item key={item.id} item={item} updateTodo={updateTodo} deleteTodo={deleteTodo}></Item>
        ))}
      </ul>
    )
  }
}

// day18-vue2.0/01-web0521-vue/03-src-todos案例-传统实现/components/List.vue
<template>
  <ul class="todo-main">
    <Item v-for="(item) in todoList" :key="item.id" :todo="item" :updateTodo="updateTodo" :deleteTodo="deleteTodo"></Item>
  </ul>
</template>

<script>
import Item from './Item'
export default {
  props: ['todoList', "updateTodo","deleteTodo"],
  components: {
    Item,
  },
}
</script>

<style>
/*main*/
.todo-main {
  margin-left: 0px;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding: 0px;
}

.todo-empty {
  height: 40px;
  line-height: 40px;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding-left: 5px;
  margin-top: 10px;
}
</style>
