// day08-react/01-web0521/02-src-todos案例-hooks版/components/Footer/Footer.js
import React from 'react'
import PubSub from 'pubsub-js'
import './Footer.css'
export default function Footer(props) {
  const { list } = props
  const allTotal = list.length
  const doneTotal = list.filter((item) => item.isDone).length
  return (
    <div className="todo-footer">
      <label>
        <input
          type="checkbox"
          checked={allTotal === doneTotal}
          onChange={(e) => {
            PubSub.publish('checkall', e.target.checked)
          }}
        />
      </label>
      <span>
        <span>已完成 {doneTotal}</span> / 全部 {allTotal}
      </span>
      <button className="btn btn-danger" onClick={()=>{
        PubSub.publish('deleteDone')
      }}>清除已完成任务</button>
    </div>
  )
}

// day18-vue2.0/01-web0521-vue/04-src-todos案例-全局事件总线和自定义事件/components/Footer.vue
<template>
  <div class="todo-footer">
    <label>
      <input type="checkbox" v-bind:checked="doneTotal === allTotal" @change="updateAll"/>
    </label>
    <span> <span>已完成{{doneTotal}}</span> / 全部{{allTotal}} </span>
    <button class="btn btn-danger" @click="deleteAllDone">清除已完成任务</button>
  </div>
</template>

<script>
export default {
  // props: ['doneTotal','allTotal','updateAll',"deleteAllDone"]
  props: ['doneTotal','allTotal'],
  methods:{
    updateAll(e){
      this.$emit('updateAll', e.target.checked)
    },
    deleteAllDone(){
      this.$emit('deleteAllDone')
    }
  }
}
</script>

<style>
/*footer*/
.todo-footer {
  height: 40px;
  line-height: 40px;
  padding-left: 6px;
  margin-top: 5px;
}

.todo-footer label {
  display: inline-block;
  margin-right: 20px;
  cursor: pointer;
}

.todo-footer label input {
  position: relative;
  top: -1px;
  vertical-align: middle;
  margin-right: 5px;
}

.todo-footer button {
  float: right;
  margin-top: 5px;
}
</style>
