// day09-react/01-web0521/07-src-路由案例/pages/Message/index.js
import React, { Component } from 'react'
import { Route, Link } from 'react-router-dom'
import Detail from '../Detail'

export default class index extends Component {
  render() {
    return (
      <div>
        <ul>
          <li>
            <Link to="/home/message/1">message001</Link>
          </li>
          <li>
            <Link to="/home/message/2">message002</Link>
          </li>
          <li>
            <Link to="/home/message/3">message003</Link>
          </li>
        </ul>
        <button
          onClick={() => {
            this.props.history.push('/home/message/4')
          }}
        >
          添加
        </button>
        <button
          onClick={() => {
            this.props.history.replace('/home/message/5')
          }}
        >
          替换
        </button>
        <Route path="/home/message/:id" component={Detail}></Route>
      </div>
    )
  }
}

// day21-vue-router/01-web0521-vue/05-src-路由案例/pages/Message/index.vue
<template>
   <div>
        <ul>
          <li>
            <router-link to='/home/message/detail/1'>message001</router-link>
          </li>
          <li>
            <router-link to='/home/message/detail/2'>message002</router-link>
          </li>
          <li>
            <router-link to='/home/message/detail/3'>message003</router-link>
          </li>
        </ul>
        <button @click="$router.push({name:'detail',params:{id: 4}})">添加</button>
        <button @click="$router.replace({name:'detail',params:{id: 5}})">>替换</button>
        <router-view></router-view>
      </div>
</template>

<script>
import Detail from '../Detail'
export default {
    components:{
        Detail
    }
}
</script>

<style>

</style>
