// day21-vue-router/01-web0521-vue/05-src-路由案例/pages/Home/index.vue
<template>
  <div>
        <h2>Home组件内容</h2>
        <div>
          <ul className='nav nav-tabs'>
            <li>
              <router-link to='/home/news'>News</router-link>
            </li>
            <li>
              <router-link to='/home/message'>Message</router-link>
            </li>
          </ul>
          <div>
            <div>
             <router-view></router-view>
            </div>
          </div>
        </div>
      </div>
</template>

<script>
import News from '../News/index'
import Message from '../Message/index'
export default {
    components:{
        News,
        Message
    }
}
</script>

<style>

</style>

// day09-react/01-web0521/07-src-路由案例/pages/Home/index.js
import React, { Component } from 'react'
import { Link, Route } from 'react-router-dom'
import Message from '../Message'
import News from '../News'

export default class Home extends Component {
  render() {
    return (
      <div>
        <h2>Home组件内容</h2>
        <div>
          <ul className="nav nav-tabs">
            <li>
              <Link to="/home/news">News</Link>
            </li>
            <li>
              <Link to="/home/message">Message</Link>
            </li>
          </ul>
          <div>
            <div>
              {/* <News></News>
              <Message></Message> */}
              <Route path="/home/news" component={News}></Route>
              <Route path="/home/message" component={Message}></Route>
            </div>
          </div>
        </div>
      </div>
    )
  }
}
